#!/bin/bash

yellow_text() {
    echo -e "\e[33m$1\e[0m"
}

get_system_info() {
    echo "OS: $(uname -o)"
    echo "Kernel: $(uname -r)"
    echo "Shell: $SHELL"
    echo "WM/DE: $XDG_CURRENT_DESKTOP"
    echo "Terminal: $TERM"
    echo "CPU: $(lscpu | grep 'Model name' | awk -F ':' '{print $2}' | xargs)"
    echo "GPU: $(lspci | grep -i 'vga\|3d\|2d' | awk -F ':' '{print $3}' | xargs)"
}

ascii_art=(
    "              @@@@@@@@@@@@              "
    "         .@@@@            @@@@.         "
    "       @@@-     --.          :@@@       "
    "     @@@    *    .      #@      @@@     "
    "    @@         .                  @@    "
    "  @@@                   .     .    @@@  "
    " :@@ @:@@=   @@@@.         @@@.     @@: "
    " @@   .  .@@@@@@@*      .@@@-@@@@@   @@ "
    " @     .                   +.     .   @ "
    "@@      .#+ + .-@%           #.  .    @@"
    "@@         @@                  @.     @@"
    "@@           @ @:=+..        =@@@     @@"
    "@@           @@@  #    @ *  @@@ #     @@"
    " @            @@@@@@@@@@@@@@@@@       @ "
    " @@             @@@@@@@@@@@@         @@ "
    " :@@                                @@= "
    "  @@@       @        -:*     @     @@@  "
    "   .@@      ##.              @    @@.   "
    "     @@@      @+@=:         @   @@@     "
    "       @@@      . :@#.#@@-    @@@       "
    "         =@@@@            @@@@+         "
    "             :@@@@@@@@@@@@:             "
)

system_info=$(get_system_info)

ascii_width=$(wc -L <<< "${ascii_art[0]}")

IFS=$'\n'
for i in "${!ascii_art[@]}"; do
    yellow_text "${ascii_art[$i]}"
    if [ "$i" -lt "$(echo "$system_info" | wc -l)" ]; then
        info_line=$(echo "$system_info" | sed -n "$((i+1))p")
        printf "%*s%s\n" $((ascii_width + 5)) "" "$info_line"
    fi
done
